### ISSUE TITLE
Remove all references to Visual Studio Team Services

### ISSUE THREAD

**Issue by jessehouwing** [ALM-Rangers/azure-boards-kanban-tools#10]
* Rename all references to: 
   * [x] VSTS => Azure DevOps
   * [x] TFS => Azure DevOps Server
   * [x] Team Foundation Server => Azure DevOps Server
   * [x] Visual Studio Team Services => Azure DevOps Server
   * [x] Work Hub => Azure Boards

 * [x] Update SDK to reference the azure-devops sdk.

**Comment by madkoo** [comment]
I am closing this issue as this has been fixed with the latest release of the extension.
Feel free to create a new issue if problem still persists.
