### ISSUE TITLE
Bug: Updating backlogs keeps spinning

### ISSUE THREAD

**Issue by jessehouwing** [ALM-Rangers/azure-boards-kanban-tools#12]
![image](https://user-images.githubusercontent.com/4173387/55066733-a40e1b00-507e-11e9-8a19-d0d33fa57388.png)

**Comment by jessehouwing** [comment]
Caused by misconfigured source board. Should stop spinning on error and present issue:

![image](https://user-images.githubusercontent.com/4173387/55067086-5c3bc380-507f-11e9-8483-7ac89bf3e577.png)

![image](https://user-images.githubusercontent.com/4173387/55067120-6fe72a00-507f-11e9-8af4-bbb762724c34.png)

**Comment by madkoo** [comment]
I am closing this issue as this has been fixed with the latest release of the extension.
Feel free to create a new issue if problem still persists.
