### ISSUE TITLE
Please add license information

### ISSUE THREAD

**Issue by CarinaNeu** [ALM-Rangers/azure-boards-kanban-tools#20]
Please add the license information for this extension. 
Thank you!

**Comment by KarlDemel** [comment]
Same here. Pls add license info. Thx.

**Comment by KarlD99** [comment]
May I ask why this issue was closed without giving any further information?

**Comment by jessehouwing** [comment]
Cause I added the license.

**Comment by KarlD99** [comment]
Pls disregard my question. Found the license.
