### ISSUE TITLE
Number appended to copied swim lanes

### ISSUE THREAD

**Issue by chown-your-poptarts** [ALM-Rangers/azure-boards-kanban-tools#22]
For some reason a large number gets pre-appended to the copied swim lanes.

![Untitled](https://user-images.githubusercontent.com/7661359/57234432-925d5300-6fee-11e9-8a73-41dc236c8809.png)

**Comment by joebieker916** [comment]
Is there a solution to this?

**Comment by jessehouwing** [comment]
I haven't been able to reproduce this issue. Can you provide clearer steps to reproduce?

**Comment by jessehouwing** [comment]
I may not be hitting this because I'm running on Azure Devops Server 2020 or on the service, this looks like TFS 2017 in the screenshots.

**Comment by madkoo** [comment]
I am closing this issue as this has been fixed with the latest release of the extension.
Feel free to create a new issue if problem still persists.
