### ISSUE TITLE
Copy from/to another team not working

### ISSUE THREAD

**Issue by jkrohn73** [ALM-Rangers/azure-boards-kanban-tools#23]
Hi,

Copy from/to another team is not working with the following setup:
* Azure Devops
* Admin permissions (organisation, project and team level)
* Customised CMMI process (bugs as requirements)
* Board's have a couple of doing/done columns
* No iterations assigned, but multiple teams, hence areas
* The following error was triggered when trying to perform the copy
kanbanDialog.js:29 Uncaught (in promise) TFS.WebApi.Exception: TF1530014: The card settings are invalid. Error message: Card type 'Bug' does not exist on this board.
    at g (https://cdn.vsassets.io/bundles/vss-bundle-ext-core-v_S4Z47nwbh6DZ3lCIOrXDL4WbkhPFU9KExlwHhyV57k=:265:499)
    at https://cdn.vsassets.io/bundles/vss-bundle-ext-core-v_S4Z47nwbh6DZ3lCIOrXDL4WbkhPFU9KExlwHhyV57k=:265:3594
    at nt (https://cdn.vsassets.io/bundles/vss-bundle-ext-core-v_S4Z47nwbh6DZ3lCIOrXDL4WbkhPFU9KExlwHhyV57k=:265:763)
    at https://cdn.vsassets.io/bundles/vss-bundle-ext-core-v_S4Z47nwbh6DZ3lCIOrXDL4WbkhPFU9KExlwHhyV57k=:265:3526
    at l (https://cdn.vsassets.io/bundles/vss-bundle-ext-core-v_S4Z47nwbh6DZ3lCIOrXDL4WbkhPFU9KExlwHhyV57k=:233:8126)
    at https://cdn.vsassets.io/bundles/vss-bundle-ext-core-v_S4Z47nwbh6DZ3lCIOrXDL4WbkhPFU9KExlwHhyV57k=:233:8352
    at t.when (https://cdn.vsassets.io/bundles/vss-bundle-ext-core-v_S4Z47nwbh6DZ3lCIOrXDL4WbkhPFU9KExlwHhyV57k=:233:3784)
    at t.u.promiseDispatch (https://cdn.vsassets.io/bundles/vss-bundle-ext-core-v_S4Z47nwbh6DZ3lCIOrXDL4WbkhPFU9KExlwHhyV57k=:233:2828)
    at https://cdn.vsassets.io/bundles/vss-bundle-ext-core-v_S4Z47nwbh6DZ3lCIOrXDL4WbkhPFU9KExlwHhyV57k=:233:1653
    at MessagePort.t (https://cdn.vsassets.io/bundles/vss-bundle-ext-core-v_S4Z47nwbh6DZ3lCIOrXDL4WbkhPFU9KExlwHhyV57k=:233:5777)

Happy to webex the issue through with you if that helps so you can see specifically how our CMMI project is set up.

**Comment by jessehouwing** [comment]
Hmmm this may have to do with the Bugs on the Backlog setting. Thanks for the details. Let me see if I can find anyone who can look into this. Vacation season has started.

**Comment by jessehouwing** [comment]
If I manually ensure the Bug as requirement is set on the target board, it works for me without errors... 

* Are you mapping states as part of the copy-to action?
* XML or inherited process?
* What permissions do you have on either board?
  * [ ] Project Collection Admin?
  * [ ] Project Admin?
  * [ ] Team Admin?
  * [ ] Contributor?
 * Any chance you could post screenshots of the board config so I may create a repro project?

**Comment by jkrohn73** [comment]
Not sure what you mean by mapping states. I only have an existing team with a hand full of bugs in it and minor additional board columns with associated mapped states, and created a new team (which has the default states/board columns unchanged). 
You will notice in the screenshot below that some board columns share the same state however. I didnt want to change any states just in case it affected our existing charts, which are based off state, not board column.
This is all that I set on the tool. Not much else you could set.
![image](https://user-images.githubusercontent.com/52655179/60821458-e7803580-a1e6-11e9-974e-17853c7f57f6.png)
Project uses an inherited CMMI process.
I'm the Project Admin at the project level, and the team admin for both teams.
This is the team config for the team config I'm trying to copy..
![image](https://user-images.githubusercontent.com/52655179/60821190-6163ef00-a1e6-11e9-8a5e-a335202570fc.png)

**Comment by jkrohn73** [comment]
For now I was just trying to keep it basic, so only checked Requirements for the Apply settings at the following levels listbox.

**Comment by jkrohn73** [comment]
OK, just had a play around, and figured out what the issue is. When you create new teams, the default setting for bugs is "Bugs are managed with tasks". Yet the project I was copying from was set as "Bugs are managed with Requirements". When I changed the new team to be managed by requirements also, then the issue was resolved.
Ideally a nice error message to advise you of this at a minimum would be nice. Ideally it should just change the new team setting to the same as the one that you're trying to copy from. Now that I know, I'll manually update it when I create a new team prior to trying to perform the copy.

**Comment by jessehouwing** [comment]
Thanks for confirming.

**Comment by jessehouwing** [comment]
Update rolling out to the marketplace right now. May need to crtl-reload to take immediate effect.

**Comment by jkrohn73** [comment]
Thanks for that. Much appreciated.

**Comment by jessehouwing** [comment]
Looks like there are a couple of column mapping issues with this scenario as well. Need to dig into that some other time.
