### ISSUE TITLE
"Loading teams" spins forever

### ISSUE THREAD

**Issue by kirstenclappers** [ALM-Rangers/azure-boards-kanban-tools#30]
Just installed this and keen to get it working, but when I open the Kanban Tools the 'Loading teams' icon just keeps spinning.

Its a new project in Azure DevOps, I am the project administrator and the project has a Kanban process. However it is failing in any of our projects, not just this one.

In the browser dev tools, I can see that common_chunks.js is failing to load. (url is https://alm-devops-rangers.gallerycdn.vsassets.io/extensions/alm-devops-rangers/kanbanboardtools/1.1.130/1570623225049/src/common_chunks.js and error message is BlobNotFound - The specified blob does not exist. RequestId:822ef460-a01e-0008-630d-84fbd8000000 Time:2019-10-16T10:35:55.2819648Z)

There is also an error about an invalid instrumentation key from https://dc.services.visualstudio.com/v2/track

**Comment by jessehouwing** [comment]
CDN for extensions has been very inconsistent the past few days. I'll try
pushing a new version to see if that fixes it.

**Comment by jessehouwing** [comment]
Pushed a new version (with no changes) and that seems to work on my account:

![image](https://user-images.githubusercontent.com/4173387/66921949-6bd42700-f026-11e9-9b1d-594e2687d27d.png)

**Comment by kirstenclappers** [comment]
Thanks for looking into this. I'm afraid on my account it's still spinning out! Still can't load the common_chunks.js


________________________________

**Comment by jessehouwing** [comment]
Could you capture a fiddler trace so I can share it with the Visual Studio
Marketplace team?

**Comment by kirstenclappers** [comment]
Sorry I haven’t been in work to reply!

My colleague ran it and it worked fine, and bizarrely its been fine for me too since then! Like literally timing out for me, he ran it successfully, and then my next attempt seconds later worked – magic :-D

**Comment by RasmusKjellerupPedersen** [comment]
I also have this issue and have had it the last weeks time:-( Any ideas

**Comment by jessehouwing** [comment]
Not without a fiddler trace giving us more info where things are stalling.

**Comment by techsavvycarla** [comment]
> Not without a fiddler trace giving us more info where things are stalling.

Do you still need a fiddler trace for this? I would be happy to provide it as I am hitting this same issue.

**Comment by jessehouwing** [comment]
Yups a trace would be tremendously helpful. But I don't know who will be able to pick up the work, I'm currently moving houses and have zero bandwidth.
