### ISSUE TITLE
"Loading teams" spins forever (Still a problem)

### ISSUE THREAD

**Issue by RasmusKjellerupPedersen** [ALM-Rangers/azure-boards-kanban-tools#31]
Hi

As indicated in an allready closed thread then I as others dont get any options for copy since the "Loading teams" waiting icon spins forever.

Any options for solving this?

Thank you in advance

Best Regards

Rasmus Pedersen
Denmark

**Comment by jessehouwing** [comment]
As mentioned in the other issue. To diagnose this I need one of the following:

 * A fiddler trace of that captures the problem.
 * A chrome developer console trace as the problem happens
 * Access to an account that exhibits the issue
 * A screenshare with someone who can repro the issue.
 * An extensive overview of the customization made to the process template and the team's board.

I am currently not seeing this behavior on CMMI, Scrum or Agile templates in my or the alm-rangers accounts.

I understand what you are seeing isn't what you'd expect the thing to do, but I do not have enough information to repro the issue by far.

**Comment by RasmusKjellerupPedersen** [comment]
![KanBan - Loading teams problem](https://user-images.githubusercontent.com/5724243/69956186-9d824e00-14ff-11ea-92bf-b9026ab2020e.png)

**Comment by jessehouwing** [comment]
Looks like I can repro this on a Agile template project with a SINGLE team. As soon as I create an additional team in the project, it works. Can you verify this?

**Comment by RasmusKjellerupPedersen** [comment]
Okay that seems to work for me. So yes confirmed.

Though I now see that this is not solving what I thought it would.

I was trying to copy setup to other projects in the organization. So this tool seems to copy to another team and not to another project?

Thank you in advance

**Comment by jessehouwing** [comment]
Correct, at the moment only within a single team project. The number of dependencies on existing tags, fields etc is a nightmare... It has always been the plan for a v2 to be able to download the mapping file as a json file.

**Comment by RasmusKjellerupPedersen** [comment]
Okay great:-) Thank you for your  good support.

...and good luck with V.2 and we are standby while I have 30+ projects in same organization and would be nice to just copy the structure to whatever project
