### ISSUE TITLE
Brush Icon disappeared 

### ISSUE THREAD

**Issue by GingerBr** [ALM-Rangers/azure-boards-kanban-tools#39]
It seems that since the latest ADO update, the brush icon has disappeared from the boards.  So there is no way to access this tool.  Can you advise if this is the same for other users?  The extension is still installed (latest version) and enabled and this is happening in all our ADO orgs.

**Comment by jessehouwing** [comment]
It's working for me, but CDN is very slow at the moment:

![image](https://user-images.githubusercontent.com/4173387/102252835-de7cb300-3f06-11eb-92c2-09ababdfbf81.png)

Maybe do a hard-refresh of the page?

**Comment by GingerBr** [comment]
Sorry, I should have said that this is affecting all users in our ADO orgs, not just me.  Refresh/clearing cache makes no difference.

**Comment by jessehouwing** [comment]
Any messages in the browser console?

**Comment by GingerBr** [comment]
So, I installed the extension in a couple of our other orgs that didn't yet have it installed and the brush icon appears and it works. However, in the couple of orgs that already had it installed, it still doesn't appear despite uninstalling and reinstalling.  The browser console output does show the following error in those orgs:
`GET https://alm-devops-rangers.gallerycdn.vsassets.io/extensions/alm-devops-rangers/kanbanboardtools/1.1.131/1571230848584/src/common_chunks.js net::ERR_ABORTED 404 (Not Found)`

**Comment by jessehouwing** [comment]
That's an error in the Azure Devops CDN for your organisation. I'll raise
the issue with the product team, nothing I can do about it at the moment.

**Comment by jdshkolnik** [comment]
We're not seeing it either.

**Comment by GingerBr** [comment]
Hi @jessehouwing, we're still seeing this issue in the majority of our orgs, but it does work in some.  There doesn't seem to be a pattern to the region the org is hosted in.  We've done a quick analysis:

Domain | Installed | Brush   Icon
-- | -- | --
Central   US | Y | N
West   Europe | Y | N
East   US 2 | Y | N
UK   South | Y | Y
UK   South | Y | Y
UK   South | Y | N
UK   South | Y | Y
UK   South | Y | Y
UK   South | Y | Y
UK   South | Y | Y
West   Europe | Y | N
UK   South | Y | Y
UK   South | Y | Y
UK   South | Y | Y

**Comment by jessehouwing** [comment]
This must be an issue at the Azure DevOps CDN or something. I'm forwarding
this to MSFT.

**Comment by jdshkolnik** [comment]
@jessehouwing I already have an ongoing conversation with them. I'll loop you in. Is your Xpirit email address still good?

**Comment by GingerBr** [comment]
Thanks @jdshkolnik @jessehouwing

**Comment by pkuma-msft** [comment]
Hello, when I looked at the extension package version 1.1.131 I see that the file common_chunks.js isn't present in the extension package, while the file kanban_tools.html still refers to it. That's is likely the reason for the 404, can someone check and confirm this?

Also, if anyone is able to repro this issue consistently, would you mind sharing a fiddler network trace or chrome dev tools network trace (.har) file for us to investigate this further?

**Comment by ramrajesh** [comment]
@pkuma-msft - Ashley from BP shared the fiddle trace with me and I have sent it to you through email. I don't want to share that in the public issue here. Can you please take a look?

**Comment by pkuma-msft** [comment]
Thanks for sharing the fiddler trace @ramrajesh. The only difference I see between the _working_ trace and the _not working_ trace is that in the working trace there is an extra network call to `brush.png`

**Not working trace**
![image](https://user-images.githubusercontent.com/13727302/116246039-38c83300-a787-11eb-9059-844ba4320b1f.png)

**Working trace**
![image](https://user-images.githubusercontent.com/13727302/116246122-50072080-a787-11eb-83fc-003553925855.png)

@ramrajesh as to why the network call itself is not happening in the _not working_ case maybe the web platform team can take a look at?

**Comment by jochenbrandt** [comment]
Hello,
we currently also have the problem that the brush icon is not displayed. In the console I get an error when retrieving the common_chunks.js. 

![image](https://user-images.githubusercontent.com/31241232/126497763-da9c2b0f-e993-4703-b8e7-3e823414fa8e.png)

https://alm-devops-rangers.gallerycdn.vsassets.io/extensions/alm-devops-rangers/kanbanboardtools/1.1.131/1571230848584/src/common_chunks.js

When calling it from the browser I get the following error message

![image](https://user-images.githubusercontent.com/31241232/126497586-a7ae65c8-19cf-46a9-adc0-aab300a20dd2.png)

**Comment by pkuma-msft** [comment]
Hello, can the owner of https://marketplace.visualstudio.com/items?itemName=alm-devops-rangers.KanbanBoardTools this extension confirm that the `common_chunks.js` file is indeed present in the extension package version `1.1.131` that was published? When i download the .vsix package from CDN and open it up, I don't see the `common_chunks.js` file in it.

**Comment by MOlausson** [comment]
@pkuma-msft we've looked at the missing file but in our tests it didn't change the behavior. We're looking into other possibilities to the problem so hope we can have some good news soon.

**Comment by MOlausson** [comment]
So we've finally figured out what was happening here. It turned out not to be a CDN issue or something in the extension itself. Instead it was an unfortunate situation where the configuration of another extension causing the kanban extension not to load. We've worked with the author of the other extension who has released an update so the two extensions now can coexist. Case closed, finally.

**Comment by MOlausson** [comment]
So we've finally figured out what was happening here. It turned out not to be a CDN issue or something in the extension itself. Instead it was an unfortunate situation where the configuration of another extension causing the kanban extension not to load. We've worked with the author of the other extension who has released an update so the two extensions now can coexist. Case closed, finally.
