### ISSUE TITLE
Azure Boards Kanban Tools is not working

### ISSUE THREAD

**Issue by twillliams** [ALM-Rangers/azure-boards-kanban-tools#49]
<img width="792" alt="2021-08-30 14_09_15-CS Testing Demo Sandbox Team Test Issues Board - Boards" src="https://user-images.githubusercontent.com/84200641/131384759-ea7cfe8d-a2ea-42a1-b36f-23b519c81183.png">
<img width="767" alt="2021-08-30 14_08_23-UMC Sandbox Project Team Test Issues Board - Boards" src="https://user-images.githubusercontent.com/84200641/131384870-a9542cd4-ba60-4028-9078-4d7e5182a502.png">

**Comment by jessehouwing** [comment]
Well need more details than this.

Any messages on the browser console?
What were you trying to do?
What happened?
What didn't happen?

**Comment by twillliams** [comment]
I am trying to copy the layout in the attachment "Source Board" to the "Destination Board".  The columns are not copying.

Toya Williams
Collaborative Solutions
+1(704) 674-8484

**Comment by MOlausson** [comment]
@twillliams Has this been resolved?

**Comment by twillliams** [comment]
It has not, I am working on sending you the details with screenshots by tomorrow.

Toya Williams
Collaborative Solutions
+1(704) 674-8484

**Comment by MOlausson** [comment]
Great. I think for the attachments to come through you should add them to the issue from the web ui. Also check that you have permissions in the target project to do the expected customizations, you can try doing it manually if you are not sure.

**Comment by madkoo** [comment]
I am closing this issue as this has been fixed with the latest release of the extension.
Feel free to create a new issue if problem still persists.
