### ISSUE TITLE
Azure Kanban Tool Reporting Done without performing any action

### ISSUE THREAD

**Issue by ChristopherSteven-HP** [ALM-Rangers/azure-boards-kanban-tools#52]
I am getting this on the console
![image](https://user-images.githubusercontent.com/63609533/138119253-664a80e2-7a57-4cba-82b3-4f8a6a7a44d5.png)

Tool Settings
![image](https://user-images.githubusercontent.com/63609533/138119462-394279dd-5534-4976-9427-d2488c6b6c45.png)

Work Around:
Create a generic Rule in your  backlog settings for each area (epics/features/Backlog)

**Comment by MOlausson** [comment]
@ChristopherSteven-HP thanks for reporting, we'll investigate. I'll post an update here in a couple of days.

**Comment by madkoo** [comment]
I am closing this issue as this has been fixed with the latest release of the extension.
Feel free to create a new issue if problem still persists.
