### ISSUE TITLE
Teams not loading

### ISSUE THREAD

**Issue by alenasok** [ALM-Rangers/azure-boards-kanban-tools#53]
When I try to use azure-boards-kanban-tools I can't select a team to copy settings (see only spinning load icon). How to fix it?

**Comment by MOlausson** [comment]
This seem to happen if there's only one team in the target project. Can you open the developer tools in the browser (F12) and check for any errors in the console or network log?

**Comment by alenasok** [comment]
There are a lot of teams in project
In the console these mistakes:  Uncought (in promise) no team found

**Comment by MOlausson** [comment]
Ok, understood. Can you detail the way you try to do the copy? Is this inside the same project?

**Comment by madkoo** [comment]
I am closing this issue as this has been fixed with the latest release of the extension.
Feel free to create a new issue if problem still persists.
